### PR TITLE
changeVersion

### PR DESCRIPTION
**Pull request by lldelisle**
Set version to 0.0.1
It would be good also to tag a version in github.
Finally, would it be possible to update https://tanaylab.github.io/umi4cpackage/index.html?
Thanks

### CODE REVIEW

**Comment by aviezerl** [comment]
Good idea, thanks again.

**Comment by lldelisle** [comment]
Is there a way to display the second vignette on the website?

**Comment by lldelisle** [comment]
I just fund a typo in the installation procedure.
It should be:
```
devtools::install_github("tanaylab/umi4cpackage", build_vignette = TRUE)
```

**Comment by aviezerl** [comment]
Fixed the typo and rebuilt the site with the missing vignette. 

Thanks again!
Aviezer

**Comment by lldelisle** [comment]
Thanks.
I will take care of the bioconda release.

**Pull request merged**
